service: virgo

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs6.10
  iamRoleStatements:
    - Effect: Allow
      Resource: arn:aws:s3:::${env:AWS_S3_BUCKET}/processed*
      Action:
        - s3:ListBucket
        - s3:PutObject
        - s3:DeleteObject
        - s3:GetObjectAcl
        - s3:ListBucketMultipartUploads
        - s3:ListMultipartUploadParts
        - s3:PutObject
        - s3:PutObjectAcl
        - s3:PutObjectTagging
        - s3:PutObjectVersionAcl
        - s3:PutObjectVersionTagging

functions:
  exec:
    handler: handler.exec
    events:
      - http:
          method: get
          path: exec

  debug:
    handler: handler.debug
    events:
      - http:
          method: get
          path: debug
